### ISSUE TITLE
Suggestion for a change-tracker wiki

### ISSUE THREAD

**Issue by texadactyl** [4xxi/mercury#14]
Its not necessary to create a full-blown wiki for this project.  But, I thought that it might be useful to track changes in human-readable form.  Not sure how you two feel about that.

I just wrote up an idea as an after-thought today:
https://github.com/texadactyl/mercury/wiki/Change-History-for-Project-Mercury

**Comment by idovgalyov-4xxi** [comment]
Hello, Richard!
We actually thought about some kind of separate changelog file included in the repo, but not seriously because we made not so many changes before, and most of them were done for our needs in other projects...
However, your idea makes sence due to recent activity on the project.

**Comment by texadactyl** [comment]
Wiki page created.
