### ISSUE TITLE
Total number of bodies exceeds NMAX (ONLY in close6 execution)

### ISSUE THREAD

**Issue by sretsa** [4xxi/mercury#21]
Hi everyone, 

I have realized during test of hundreds small particles that when the number of bodies in small.in is greater than 200, close6 execution crashes giving the following error:
 ERROR: The total number of bodies exceeds NMAX.
I have made the pertinent changes in mercury.inc and swift.inc. The mercury6 and element6 executions work fine with any number of small bodies (always according to the specified limits on the .inc files) but close6 execution crashes at the 200th small body. For example, if the Moon is where all small bodies are having a close encounter (they launch from the Moon's surface) the list of the close encounter (dmin, orbital elements, etc.) is completed until 200th body.

I cannot figure out why this is happening. Any help will be much welcomed! thanks

PS: Current parameters defined:
in swift.inc
NPLMAX = 2002
 NTPMAX = 2000

 in mercury.inc
      parameter (NMAX = 4003)
      parameter (CMAX = 8000)
      parameter (NMESS = 100)
      parameter (HUGE = 9.9d29)
      parameter (NFILES = 50)

See attachments for big.in, small.in, param.in
[i_VgitTEST.tar.gz](https://github.com/4xxi/mercury/files/4344572/i_VgitTEST.tar.gz)

**Comment by texadactyl** [comment]
The source file close6.for will not even compile with those parameter values:

```
gfortran -g -O2 -Wline-truncation -Wsurprising -Werror -o ./close6 ./close6.for
./close6.for:832:31:

  832 |         write (*,'(/,3a)') mem(121)(1:lmem(121)),mem(87)(1:lmem(87)),
      |                               1
Error: Array reference at (1) is out of bounds (121 > 100) in dimension 1 [-Werror]
./close6.for:832:43:

  832 |         write (*,'(/,3a)') mem(121)(1:lmem(121)),mem(87)(1:lmem(87)),
      |                                           1
Error: Array reference at (1) is out of bounds (121 > 100) in dimension 1 [-Werror]
./close6.for:832:43:

  832 |         write (*,'(/,3a)') mem(121)(1:lmem(121)),mem(87)(1:lmem(87)),
      |                                           1
Error: Array reference at (1) is out of bounds (121 > 100) in dimension 1 [-Werror]
./close6.for:306:37:

  306 |         write (*,'(2a,/,a,i10)') mem(121)(1:lmem(121)),
      |                                     1
Error: Array reference at (1) is out of bounds (121 > 100) in dimension 1 [-Werror]
./close6.for:306:49:

  306 |         write (*,'(2a,/,a,i10)') mem(121)(1:lmem(121)),
      |                                                 1
Error: Array reference at (1) is out of bounds (121 > 100) in dimension 1 [-Werror]
./close6.for:306:49:

  306 |         write (*,'(2a,/,a,i10)') mem(121)(1:lmem(121)),
      |                                                 1
Error: Array reference at (1) is out of bounds (121 > 100) in dimension 1 [-Werror]
./close6.for:307:30:

  307 |      %    infile(i)(1:60),mem(104)(1:lmem(104)),line_num
      |                              1
Error: Array reference at (1) is out of bounds (104 > 100) in dimension 1 [-Werror]
./close6.for:307:42:

  307 |      %    infile(i)(1:60),mem(104)(1:lmem(104)),line_num
      |                                          1
Error: Array reference at (1) is out of bounds (104 > 100) in dimension 1 [-Werror]
./close6.for:307:42:

  307 |      %    infile(i)(1:60),mem(104)(1:lmem(104)),line_num
      |                                          1
Error: Array reference at (1) is out of bounds (104 > 100) in dimension 1 [-Werror]
f951: all warnings being treated as errors
make: *** [Makefile:27: close6] Error 1

```
The problem is that parameter (NMESS = 100) will caused the miscompile.  You must have changed that.

**Comment by texadactyl** [comment]
I changes NMESS back to 200 (original value) but kept your other parameters.
```
base) elkins@biostar:~/projects/mercury-master$ mercury6
   Integrating massive bodies and particles up to the same epoch.
   Beginning the main integration.
 Date:       2119  8  6.4   dE/E: -4.79971E-13   dL/L: -2.81091E-13
 Date:       2229  2 15.8   dE/E: -4.79807E-13   dL/L: -2.61420E-13
 Date:       2338  8 24.1   dE/E: -1.97181E-13   dL/L: -1.94135E-13
 Date:       2448  2 29.3   dE/E: -4.84736E-13   dL/L: -3.12712E-13
 Date:       2557  9 11.9   dE/E: -4.15394E-13   dL/L: -2.84584E-13
 Date:       2667  3 22.5   dE/E:  3.28799E-13   dL/L: -1.55345E-13
 Date:       2776  9 28.9   dE/E:  5.13821E-13   dL/L: -1.18577E-13
 Date:       2886  4  6.5   dE/E:  3.96005E-14   dL/L: -4.56474E-13
 Date:       2995 10 18.9   dE/E:  6.32622E-14   dL/L: -4.88462E-13
 Date:       3105  5  2.0   dE/E:  1.14694E-12   dL/L: -1.31445E-13
 Date:       3214 11 10.4   dE/E:  5.12999E-13   dL/L: -4.65299E-13
 Date:       3324  5 22.7   dE/E:  2.86898E-13   dL/L: -6.88296E-13
 Date:       3433 11 30.4   dE/E: -2.41875E-13   dL/L: -8.90704E-13
   Integration complete.
(base) elkins@biostar:~/projects/mercury-master$ ls *for
close6.for  element6.for  mercury6_2.for
(base) elkins@biostar:~/projects/mercury-master$ element6
(base) elkins@biostar:~/projects/mercury-master$ close6
(base) elkins@biostar:~/projects/mercury-master$ 

```
No early terminations and no crashes.
I do not know if the results are valid.  See attached ZIP file.
[results.zip](https://github.com/4xxi/mercury/files/4339166/results.zip)

**Comment by texadactyl** [comment]
Please note that these 20-to-30-year-old Fortran programs are fragile in terms of self-diagnosing and error prevention.  You can see that they root from older Fortran programs that obeyed 80-column cards and 121-character-line printers.  

Recently, some capability towards this end has been added but the code remains far from "perfect".  If I had a magic wand, this code would be all Java or some other strong type-checking language.

I am sure that 4xxi would welcome suggestions and a helping hand if you find further areas of improvement.

**Comment by sretsa** [comment]
Hi texadactyl!
Thanks for your response.
Mine still crashes... but because your compilation is with only 2 small bodies (APOLLO and APOPHIS)  I have more than 200 (I generate them with an external programme). But I do not get why mercury6 and element6 do not crash and close6 yes.
NMESS = 200 does not solve the issue.

Regards

**Comment by sretsa** [comment]
This is the file I am using for small bodies.

[i_VgitTEST.tar.gz](https://github.com/4xxi/mercury/files/4343247/i_VgitTEST.tar.gz)

**Comment by texadactyl** [comment]
You never before mentioned big.in, param.in, and small.in.  That would have been helpful.

**Comment by sretsa** [comment]
Sorry, no, I did not mention the files specifically. I said I used 200 small bodies, which I took for granted it was clear as the name of the file usually is "small.in" for small bodies.
I will edit that for clarification.

**Comment by texadactyl** [comment]
Okay, using your versions of big.in, param.in, and small.in:

```
mercury6
   Integrating massive bodies and particles up to the same epoch.
   Beginning the main integration.
   Integration complete.
(base) elkins@biostar:~/projects/mercury-master$ element6
(base) elkins@biostar:~/projects/mercury-master$ close6
```
No aborts/crashes.
See attached ZIP of generated files.
[generated_files.zip](https://github.com/4xxi/mercury/files/4344591/generated_files.zip)

**Comment by texadactyl** [comment]
The *.in files are attached.
[in_files.zip](https://github.com/4xxi/mercury/files/4344611/in_files.zip)

**Comment by texadactyl** [comment]
Is it possible that you have made other changes than what is listed here thus far?
My mercury.inc file is attached.

[mercury.inc.txt](https://github.com/4xxi/mercury/files/4344721/mercury.inc.txt)

**Comment by sretsa** [comment]
In my case still gives the same error. I downloaded again mercury6_2.for, element6.for, and close6.for
used my .inc files (mercury.inc and swift.inc) and your input files. Still crashes at close6:

```
esther@esther-hp ~/Escritorio/mercury-master/git_trial $ ./mercury6 && ./element6
   Integrating massive bodies and particles up to the same epoch
   Beginning the main integration.
   Integration complete.
esther@esther-hp ~/Escritorio/mercury-master/git_trial $ ./close6
 ERROR: The total number of bodies exceeds NMAX.
```
May be if I could see the rest of your files, cause I do not see what is going on

**Comment by sretsa** [comment]
> Is it possible that you have made other changes than what is listed here thus far?
> My mercury.inc file is attached.
> 
> [mercury.inc.txt](https://github.com/4xxi/mercury/files/4344721/mercury.inc.txt)

I will give a look

**Comment by texadactyl** [comment]
The rest of my files are the same as the project defaults (*.sample).

**Comment by sretsa** [comment]
I have identical .inc files as the ones you just posted. And for the trial I just re-downloaded .for files

**Comment by texadactyl** [comment]
What about the *.in files that I posted?

**Comment by texadactyl** [comment]
They are essentially what you supplied.

**Comment by sretsa** [comment]
> What about the *.in files that I posted?

I used yours for the compile and execution

**Comment by texadactyl** [comment]
So, our *.inc and *.in files are identical?

**Comment by sretsa** [comment]
yes they are. I check the .txt and for the .in you used mines.
Here it is what I am using and the output. Note that all .aei files are created but when close6 is executed, 48 small bodies and the first 200th Moon close encounters.

[git_in.tar.gz](https://github.com/4xxi/mercury/files/4344763/git_in.tar.gz)
[git_output.tar.gz](https://github.com/4xxi/mercury/files/4344764/git_output.tar.gz)

**Comment by texadactyl** [comment]
So, starting over .....
```
(base) elkins@biostar:~/projects/mercury-master$ make rm-gen
rm -f ./{ *.dmp *.clo *.out *.tmp *.aei } 2> /dev/null
(base) elkins@biostar:~/projects/mercury-master$ make unbuild
rm -f ./element6 ./close6 ./mercury6
(base) elkins@biostar:~/projects/mercury-master$ make build
gfortran -g -O2 -Wline-truncation -Wsurprising -Werror -o ./close6 ./close6.for
gfortran -g -O2 -Wline-truncation -Wsurprising -Werror -o ./element6 ./element6.for
gfortran -g -O2 -Wline-truncation -Wsurprising -Werror -o ./mercury6 ./mercury6_2.for
(base) elkins@biostar:~/projects/mercury-master$ mercury6
   Integrating massive bodies and particles up to the same epoch.
   Beginning the main integration.
   Integration complete.
(base) elkins@biostar:~/projects/mercury-master$ element6
(base) elkins@biostar:~/projects/mercury-master$ close6
(base) elkins@biostar:~/projects/mercury-master$ 

```
No crashes.  *.in files and generated files are attached.
[in_files.zip](https://github.com/4xxi/mercury/files/4344771/in_files.zip)

[generated_files.zip](https://github.com/4xxi/mercury/files/4344768/generated_files.zip)

**Comment by texadactyl** [comment]
1. Remove existing generated files: make rm-gen
2. Un-build Fortran programs: make unbuild
3. Build Fortran programs: make build
4. mercury6
5. element6
6. close6

That's what you did too?

**Comment by texadactyl** [comment]
Steps 2 & 3 are only necessary if an *.inc file is changed.

**Comment by sretsa** [comment]
> 1. Remove existing generated files: make rm-gen
> 2. Un-build Fortran programs: make unbuild
> 3. Build Fortran programs: make build
> 4. mercury6
> 5. element6
> 6. close6
> 
> That's what you did too?

No,  I was not doing steps 2 & 3.

**Comment by sretsa** [comment]
> Steps 2 & 3 are only necessary if an *.inc file is changed.

Now it compiles

**Comment by texadactyl** [comment]
Okay, that means that you changed mercury.inc after you compiled but did not recompile to pick up the changes.

But, excellent.  I hope that your results are interesting now!

**Comment by texadactyl** [comment]
What language do you normally program in?  If C, this is like changing a .h file but not recompiling the dependent *.c files, right?  

All's well that ends well.

**Comment by sretsa** [comment]
Many thanks!! I did not know about these 2 commands of building/unbuilding. I checked the Read.Me and that is not stated there. May be I missed it and it is stated somewhere else. Definetely thank you. I quite foreign to Fortran and I highly doubt I had figure this out on my own.
I am closing the thread. 
Regards

**Comment by texadactyl** [comment]
You are most welcome.

YES, the documentation leaves a lot to be desired.  I wrote up a separate bug report on that subject.

Happy computing!

**Comment by sretsa** [comment]
> What language do you normally program in? If C, this is like changing a .h file but not recompiling the dependent *.c files, right?
> 
> All's well that ends well.

Well, if it can be considered a programming language at all... Matlab. It was a while ago since last I had to preocupy about compilations and .h .c files on C    :S

Thanks again!

**Comment by texadactyl** [comment]
Out of curiosity, are you a Physicist?
Any association with Caltech?

**Comment by sretsa** [comment]
> Out of curiosity, are you a Physicist?
> Any association with Caltech?

Uy no. I'm from UPC (Polytechnic University of Catalonia, Spain). Master student in aerospace engineering, Space track. Actually, after the first overview on mercury6 and Chamber's paper I was a bit lost... coming from engineering some physics concepts were too tangential to completely follow the explanations!!

**Comment by sretsa** [comment]
May be nobody reads to this far but it can be helpful if someone is in the same situation... before, I was recompiling mercury only doing this (as suggested in the Read.me):
 
`esther@esther-hp ~/Escritorio/mercury-master/git_trial $ f77 -o mercury6 mercury6_2.for && f77 -o element6 element6.for && f77 -o close6 close6.for`

Instead of the steps 2 and 3 of make unbuild/build.

**Comment by texadactyl** [comment]
Best to follow steps outlined in issue #22 for preparation and execution.
Hopefully, the 4xxi team will update the README.md instructions soon.
