### ISSUE TITLE
Accuracy in simple test

### ISSUE THREAD

**Issue by evg-tyurin** [4xxi/mercury#7]
I´ve downloaded the sources and compiled them.
I left all *.in files untouched except that I changed calculation interval in param.in and set it to 100 years.
After the calculations were completed I run element6 to get output files in a readable form.
I see that the perihelion precession of Mercury is 980 arcseconds per century that is almost twice larger than the observational value.
Is it OK?

**Comment by smirik** [comment]
What integrator did you use for the calculations? It might be integration issue due to Mercury.
