### ISSUE TITLE
A few issues fixed; donationware

### ISSUE THREAD

**Issue by texadactyl** [4xxi/mercury#8]
I was referred to 4xxi/mercury by Cal Tech Professor Mike Brown.  I am one of his current Coursera students [I am a bit old for a student but Fortran IV/77 was like walking down "Memory Lane"].

I did not change any of the Science algorithms.  I left virtually all of the source code as-is.  But, I did get rid of all of the compiler warnings and fixed some obscure issues in character handling.  In addition, I created suggested sub-folders for organization (maybe you will like it).  It now compiles with a Makefile.  All of the changes are documented in file 20180507_texadactyl.txt at the same level as README.md.

Attached is a ZIP file of mercury-master.
[mercury-master.zip](https://github.com/4xxi/mercury/files/2002371/mercury-master.zip)

Best wishes ..... Richard

**Comment by smirik** [comment]
Hi Richard!

Thank you for the note. Would you like to apply these changes via Pull Request workflow? It will be the easiest way how to handle that?

Here is the instruction for them: https://help.github.com/articles/creating-a-pull-request/

**Comment by texadactyl** [comment]
I just noticed that the number of pull requests = 0.  Maybe I screwed up?

**Comment by smirik** [comment]
Yeah, still 0. You need to pull down the code (via fork), apply the changes & then send PR.

**Comment by texadactyl** [comment]
I actually had done that and somehow (?) mysteriously backed out of the Pull Request.  It's a bit of a confusing process, coming from a forked repo.  Anyhow, 2nd time's a charm.

**Comment by smirik** [comment]
Looks good. Let me & @idovgalyov test the changes & then we can merge it.

**Comment by smirik** [comment]
Merged in #11.
